name: Build CI

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - run: npx nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3

      - name: Build storybook
        run: npm run build-storybook

      - name: Set status check
        run: echo "::set-output name=BUILD_STATUS::success"

      - name: Upload status
        uses: actions/upload-artifact@v4
        with:
          name: build-status
          path: .github/build-status
