name: Storybook
on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install Dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Set Storybook URL
        id: set-url
        run: echo "STORYBOOK_URL=https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/$GITHUB_HEAD_REF" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: dist/storybook/storybook-host # output folder from `npm run build-storybook`

      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with Storybook link
        if: github.event_name == 'pull_request'
        run: |
          echo "Storybook deployed at $STORYBOOK_URL"
          gh pr comment ${{ github.event.number }} --body "Storybook deployed at $STORYBOOK_URL"
